[email_providers]

[email_providers."include:_netblocks.mimecast.com"]
name = "mimecast"
type = "security"

[email_providers."include:_spf.google.com"]
name = "google workspace"
type = "enterprise"

[email_providers."include:_spf.hostedemail.com"]
name = "tucows"
type = "hosting"

[email_providers."include:_spf.mail.ru"]
name = "mailru"
type = "webmail"

[email_providers."include:_spf.mailbox.org"]
name = "mailbox.org"
type = "webmail"

[email_providers."include:_spf.mailhostbox.com"]
name = "mailhostbox"
type = "hosting"

[email_providers."include:_spf.naver.com"]
name = "naver"
type = "webmail"

[email_providers."include:_spf.protonmail.ch"]
name = "protonmail"
type = "webmail"

[email_providers."include:_spf.salesforce.com"]
name = "salesforce"
type = "support"

[email_providers."include:_spf.simplyspamfree.com"]
name = "spamexperts"
type = "security"

[email_providers."include:_spf.stackmail.com"]
name = "steadfast"
type = "hosting"

[email_providers."include:_spf.yandex.ru"]
name = "yandex"
type = "webmail"

[email_providers."include:amazonses.com"]
name = "amazon ses"
type = "transactional"

[email_providers."include:cmail*.com"]
name = "campaign monitor"
type = "marketing"

[email_providers."include:elasticemail.com"]
name = "elasticemail"
type = "transactional"

[email_providers."include:emailsrvr.com"]
name = "rackspace"
type = "hosting"

[email_providers."include:hubspot.net"]
name = "hubspot"
type = "marketing"

[email_providers."include:icloud.com"]
name = "icloud"
type = "webmail"

[email_providers."include:mailgun.org"]
name = "mailgun"
type = "transactional"

[email_providers."include:mx.ovh.com"]
name = "ovh"
type = "hosting"

[email_providers."include:pphosted.com"]
name = "proofpoint"
type = "security"

[email_providers."include:res.cisco.com"]
name = "cisco"
type = "security"

[email_providers."include:secureserver.net"]
name = "godaddy"
type = "hosting"

[email_providers."include:secondstreetmail.com"]
name = "uplandsoftware"
type = "marketing"

[email_providers."include:sendgrid.net"]
name = "sendgrid"
type = "transactional"

[email_providers."include:servers.mcsv.net"]
name = "mailchimp"
type = "marketing"

[email_providers."include:smtp.secureserver.net"]
name = "godaddy"
type = "hosting"

[email_providers."include:sparkpostmail.com"]
name = "sparkpost"
type = "transactional"

[email_providers."include:spf.163.com"]
name = "netease"
type = "webmail"

[email_providers."include:spf.alimail.com"]
name = "alibabamail"
type = "enterprise"

[email_providers."include:spf.barracudanetworks.com"]
name = "barracuda"
type = "security"

[email_providers."include:spf.constantcontact.com"]
name = "constant contact"
type = "marketing"

[email_providers."include:spf.daum.net"]
name = "daum"
type = "webmail"

[email_providers."include:spf.dreamhost.com"]
name = "dreamhost"
type = "hosting"

[email_providers."include:spf.egress.com"]
name = "egress"
type = "security"

[email_providers."include:spf.emailsrvr.com"]
name = "rackspace"
type = "hosting"

[email_providers."include:spf.forcepoint.com"]
name = "forcepoint"
type = "security"

[email_providers."include:spf.frontapp.com"]
name = "front"
type = "support"

[email_providers."include:spf.gmx.net"]
name = "gmx"
type = "webmail"

[email_providers."include:spf.greathorn.com"]
name = "greathorn"
type = "security"

[email_providers."include:spf.helpscout.net"]
name = "helpscout"
type = "support"

[email_providers."include:spf.hetzner.com"]
name = "hetzner"
type = "hosting"

[email_providers."include:spf.hushmail.com"]
name = "hushmail"
type = "webmail"

[email_providers."include:spf.infomaniak.com"]
name = "infomaniak"
type = "hosting"

[email_providers."include:spf.intermedia.net"]
name = "intermedia"
type = "hosting"

[email_providers."include:spf.ionos.com"]
name = "ionos"
type = "hosting"

[email_providers."include:spf.klaviyomail.com"]
name = "klaviyo"
type = "marketing"

[email_providers."include:spf.mail.yahoo.com"]
name = "yahoo"
type = "webmail"

[email_providers."include:spf.mailchannels.net"]
name = "mailchannels"
type = "transactional"

[email_providers."include:spf.mailchimp.com"]
name = "mailchimp"
type = "marketing"

[email_providers."include:spf.mailcow.email"]
name = "mailcow"
type = "hosting"

[email_providers."include:spf.mailerlite.com"]
name = "mailerlite"
type = "marketing"

[email_providers."include:spf.mailfence.com"]
name = "mailfence"
type = "webmail"

[email_providers."include:spf.mailjet.com"]
name = "mailjet"
type = "transactional"

[email_providers."include:spf.mailtrap.io"]
name = "mailtrap"
type = "transactional"

[email_providers."include:spf.mandrillapp.com"]
name = "mandrill"
type = "transactional"

[email_providers."include:spf.messagelabs.com"]
name = "broadcom"
type = "security"

[email_providers."include:spf.messagingengine.com"]
name = "fastmail"
type = "hosting"

[email_providers."include:spf.migadu.com"]
name = "migadu"
type = "hosting"

[email_providers."include:spf.mtasv.net"]
name = "postmark"
type = "transactional"

[email_providers."include:spf.mxhichina.com"]
name = "alibabamail"
type = "enterprise"

[email_providers."include:spf.posteo.de"]
name = "posteo"
type = "webmail"

[email_providers."include:spf.privateemail.com"]
name = "namecheap"
type = "hosting"

[email_providers."include:spf.protection.outlook.com"]
name = "outlook"
type = "enterprise"

[email_providers."include:spf.qq.com"]
name = "tencent"
type = "webmail"

[email_providers."include:spf.reflexion.net"]
name = "sophos"
type = "security"

[email_providers."include:spf.retarus.com"]
name = "retarus"
type = "transactional"

[email_providers."include:spf.runbox.com"]
name = "runbox"
type = "webmail"

[email_providers."include:spf.sendinblue.com"]
name = "sendinblue"
type = "marketing"

[email_providers."include:spf.serverdata.net"]
name = "sherweb"
type = "hosting"

[email_providers."include:spf.sina.com"]
name = "sinamail"
type = "webmail"

[email_providers."include:spf.smtp2go.com"]
name = "smtp2go"
type = "transactional"

[email_providers."include:spf.sohu.com"]
name = "sohumail"
type = "webmail"

[email_providers."include:spf.spamexperts.com"]
name = "solarwinds"
type = "security"

[email_providers."include:spf.trendmicro.com"]
name = "trendmicro"
type = "security"

[email_providers."include:spf.tutanota.de"]
name = "tutanota"
type = "webmail"

[email_providers."include:spf.web.de"]
name = "webde"
type = "webmail"

[email_providers."include:spf.yandex.net"]
name = "yandex"
type = "webmail"

[email_providers."include:spf.zimbra.com"]
name = "zimbra"
type = "hosting"

[email_providers."include:us._netblocks.mimecast.com"]
name = "mimecast"
type = "security"

[email_providers."include:zixmail.net"]
name = "zix"
type = "security"

[email_providers."include:zoho.com"]
name = "zoho"
type = "enterprise"
